object Versions {
    const val activityCompose = "1.8.2"
    const val coreKTX = "1.12.0"
    const val runtimeKTX = "2.6.2"
    const val kotlinGradlePlugin = "1.9.10"
    const val junit = "4.13.2"
    const val testJunit = "1.1.5"
    const val testEspresso = "3.5.1"
    const val appCompat = "1.6.1"
    const val material = "1.11.0"
    const val compose = "1.4.3"
    const val composeMaterial3 = "1.1.2"
    const val composeCompiler = "1.5.7"
    const val composeBom = "2023.08.00"
    const val timber = "5.0.1"
    const val mockito = "5.8.0"
    const val hilt = "2.49"
    const val hiltNavCompose = "1.1.0"
    const val okHttp = "4.12.0"
    const val retrofit = "2.9.0"
    const val googleServices = "4.3.15"
    const val firebaseCrashlytics = "18.6.0"
    const val firebaseCrashlyticsGradle = "2.9.9"
    const val firebaseAnalytics = "21.5.0"
    const val firebaseAuth = "22.3.0"
    const val firebaseCommon = "20.4.2"
}